version: '3'

services:
  landsat8-ard:
    build:
      context: ../
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_ENDPOINT=
      - S3_BUCKET=
    command: [ "python3", "-m","landsat.worker-LS" ]