version: '3'

services:
  landsat-ard:
    build:
      context: ../
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=30000
      - AWS_ACCESS_KEY_ID=s3-proxy-not-needed
      - AWS_SECRET_ACCESS_KEY=s3-proxy-not-needed
      - AWS_DEFAULT_REGION=eu-west-2
      - S3_ENDPOINT=http://localhost:30003
      - S3_BUCKET=ard-bucket
    command: [ "python3", "-m","landsat.worker-LS" ]