apiVersion: apps/v1
kind: Deployment
metadata:
  name: ard-docker-images-landsat
spec:
  replicas: {{ .Values.numWorkerReplicasLandsat }}
  selector:
    matchLabels:
      app: ard-docker-images-landsat
  template:
    metadata:
      labels:
        app: ard-docker-images-landsat
    spec:
      containers:
      - name: s3proxy
        image: andrewgaul/s3proxy:sha-b5d090d
        env:
            - name: S3PROXY_ENDPOINT
              value: "http://0.0.0.0:80"
            - name: S3PROXY_AUTHORIZATION
              value: "none"
            - name: JCLOUDS_PROVIDER
              value: "azureblob"
            - name: JCLOUDS_IDENTITY
              value: {{ .Values.s3proxy.jcloudsIdentity | quote }}
            - name: JCLOUDS_ENDPOINT
              value: {{ .Values.s3proxy.jcloudsEndpoint | quote }}
            - name: JCLOUDS_CREDENTIAL
              value: {{ .Values.s3proxy.jcloudsCredential | quote }}