version: '3'

services:
  # redis-master:
  #   image: redis
  #   container_name: redis-master
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./redisdata:/data
  
  sentinel1-am-ard:
    build:
      context: ../
    network_mode: host
    environment:
      - LOGLEVEL=DEBUG
      - REDIS_HOST=
      - REDIS_PORT=
      - AWS_ACCESS_KEY_ID=s3-proxy-not-needed
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_ENDPOINT=
      - S3_BUCKET=
      - COPERNICUS_USERNAME=
      - COPERNICUS_PWD=
    command: ["python3", "-m","sentinel-1-backscatter-am.worker-s1-am"]