name: publish docker containers

on:
  push:
    branches: ["main","master"]
  pull_request:
    branches: ["main","master"]

jobs:
  workfinder:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_ENVIRONMENT
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Dockerhub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ivicamaticsd/catapult-ard-docker-images:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}