name: publish docker containers

on:
  push:
    branches: ["main","master","dev"]
  # pull_request:
  #   branches: ["main","master"]

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_ENVIRONMENT
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Docker pull for faster build times
#         run: docker pull ivicamaticsd/catapult-ard-docker-images:${{ env.BRANCH_NAME }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push to Dockerhub under branch ${{ env.BRANCH_NAME }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          cache-from: type=registry,ref=ivicamaticsd/catapult-ard-docker-images-build-cache .
          cache-to: type=registry,ref=ivicamaticsd/catapult-ard-docker-images-build-cache
          push: true
          tags: ivicamaticsd/catapult-ard-docker-images:${{ env.BRANCH_NAME }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
