version: '3'

services:
  # redis-master:
  #   image: redis
  #   container_name: redis-master
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - ./redisdata:/data
  
  sentinel2-ard:
    build:
      context: ../
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=30000
      - AWS_ACCESS_KEY_ID=AKIA2GUC6LBMKP5ICEV3
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_ENDPOINT=https://s3.amazonaws.com
      - S3_BUCKET=
      - COPERNICUS_USERNAME=
      - COPERNICUS_PWD=
    command: ["python3", "-m","sentinel-2-l2a.worker-s2"]